### PR TITLE
Add more useful failure message

### PR DESCRIPTION
**Pull request by michaelwebb76**
I wasted two hours getting to the bottom of this.

### CODE REVIEW

**Comment by michaelwebb76** [comment]
@samuelgiles Please take a look at this when you get a chance. This results in an error message in Rspec that actually tells you the probable cause of your issue.

**Comment by samuelgiles** [comment]
Hey @michaelwebb76, so is this looking to solve the issue of when you try and run the example on a class that hasn't called `implements_interface`?

If so, I think the error message is right, but it needs to be part of an earlier `expect` that initially checks `.says_it_implements?`, this way it will fail if you haven't called `implements_interface` for the interface given to the shared example.

E.g:
```ruby
RSpec.shared_examples 'it implements' do |interface_class|
  DOESNT_SAY_IT_IMPLEMENTS = 'You must use `implements_interface` to enforce checking of interface'

  describe "implements interface #{interface_class.name}" do
    subject(:says_it_implements) { described_class.says_it_implements?(interface_class) }
    subject(:check_it_implements) { described_class.check_it_implements(interface_class) }

    specify do
      expect(says_it_implements).to be(true), DOESNT_SAY_IT_IMPLEMENTS
      expect(check_it_implements).to be(true)
    end
  end
end
```

**Comment by michaelwebb76** [comment]
I tested it locally where I was using `include` instead of `implements_interface`. As long as it still shows that error message in that use case, I'm happy.

**Comment by samuelgiles** [comment]
@michaelwebb76 Yeah it should do because we add `. says_it_implements?` to every object where it returns false until you've called `implements_interface`. I'll add a commit to this PR and merge it in later today 👍

**Comment by samuelgiles** [comment]
@michaelwebb76 I'm closing this as I've extended upon it in https://github.com/samuelgiles/duckface/pull/5

**Pull request closed without merging**
